//! # `tracing-perfetto-sdk-schema`: Internal crate containing the raw Perfetto proto schemata.
// Everything here is generated by `prost` from upstream Perfetto protos, so
// the lints below are complaints about Perfetto's comment formatting and
// field naming, neither of which is ours to fix.
#![allow(clippy::doc_lazy_continuation, clippy::doc_overindented_list_items)]
#![allow(clippy::len_without_is_empty, clippy::large_enum_variant)]
include!(concat!(env!("OUT_DIR"), "/perfetto.protos.rs"));
#[cfg(feature = "serde")]
mod serde_impls {
    use super::*;
    // Only contains trait impls so no need to re-export
    include!(concat!(env!("OUT_DIR"), "/perfetto.protos.serde.rs"));
}
