name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Build
      run: cargo build --all
    - name: Run tests
      run: cargo test --all
  build-tokio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Build
      run: cargo build --all --features=tokio
    - name: Run tests
      run: cargo test --all --features=tokio
  build-serde:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Build
      run: cargo build --all --features=serde
    - name: Run tests
      run: cargo test --all --features=serde
  build-serde-tokio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Build
      run: cargo build --all --features=serde,tokio
    - name: Run tests
      run: cargo test --all --features=serde,tokio
